name: 'ASM Script'
description: 'Run an assembly program'

inputs:
  data:
    description: 'Data section'
    required: false
  text:
    description: 'Text section'
    required: true
  template:
    description: 'The Assmebly template'
    required: false
    default: |
      section .data
        ASM_DATA

      section .text
        ASM_TEXT

        mov rax, 60       ; syscall number for sys_exit (64-bit)
        xor rdi, rdi      ; exit status 0
        syscall           ; call kernel

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        sudo apt-get install nasm -y

    - name: 'Create Project'
      shell: bash
      run: |
        ASM_PROJECT=$(mktemp -d)
        echo "ASM_PROJECT=$ASM_PROJECT" >> $GITHUB_ENV
        cd "$ASM_PROJECT"

    - name: 'Generate Script'
      shell: bash
      working-directory: ${{ env.ASM_PROJECT }}
      run: |
        set -e

        cat << EOF > template.s
        ${{ inputs.template }}
        EOF

        DATA=$(cat << EOF
        ${{ inputs.data }}
        EOF
        )
        awk -v data="$DATA" '
        {
          gsub(/ASM_DATA/, data);
          print
        }' "template.s" > data.s

        TEXT=$(cat << EOF
        ${{ inputs.text }}
        EOF
        )
        awk -v text="$TEXT" '
        {
          gsub(/ASM_TEXT/, text);
          print
        }' "data.s" > source.s

    - name: 'Run Script'
      shell: bash
      working-directory: ${{ env.ASM_PROJECT }}
      run: |
        nasm -f elf64 source.s -o out.o
        ld out.o -o out
        ./out

