on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: klahr/asm-inline@master
        id: run
        with:
          data: |
            message db "Hello, World!", 0xA
            msg_len equ $ - message
          text: |
              mov rax, 1
              mov rdi, 1
              mov rsi, message
              mov rdx, msg_len
              syscall
